site_name: Microworkflows
site_url: https://www.microworkflows.org/
theme: mkdocs
nav:
  - Examples: examples.md
  - 'Microworkflows and ..': related.md
  - 'Orchestration vs. Choreography': orchestration-vs-choreography.md
  - Further Reading: references.md


